import type { LabApp } from './types';

const registeredLabApps: LabApp[] = [
  {
    slug: 'timezone',
    title: '时区工具',
    description: '根据设备时区实时显示本地与世界时间，一键复制常用代码时间格式。',
    category: 'tool',
    tags: ['timezone', 'tool', 'dayjs'],
    href: '/lab/timezone',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'ai',
    title: 'AI助手',
    description: 'AI 对话助手，支持api模型调用、流式回复与文本生成图片。',
    category: 'app',
    tags: ['ai', 'chat', 'streaming'],
    href: '/lab/ai',
    featured: true,
    dataSource: 'future-backend',
  },
  {
    slug: 'maplestory',
    title: '冒险岛怪物资料',
    description: '浏览冒险岛国服怀旧服怪物的属性与掉落道具，支持本地检索和排序。',
    category: 'tool',
    tags: ['maplestory', 'monster'],
    href: '/lab/maplestory',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'sudoku',
    title: '数独',
    description: '数独游戏，支持五级难度与键盘操作。',
    category: 'game',
    tags: ['game', 'sudoku', 'logic'],
    href: '/lab/sudoku',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'rss',
    title: 'RSS Reader',
    description: '聚合你的RSS订阅',
    category: 'app',
    tags: ['rss', 'reader', 'feed'],
    href: '/lab/rss',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'minesweeper',
    title: '扫雷',
    description: '经典扫雷游戏，支持预设与自定义难度。',
    category: 'game',
    tags: ['game', 'minesweeper'],
    href: '/lab/minesweeper',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'rpg',
    title: 'Adventure',
    description: '文字挂机冒险RPG游戏，选择职业，自动战斗，收集装备！',
    category: 'game',
    tags: ['game', 'rpg', 'idle'],
    href: '/game',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'skill',
    title: 'Skills',
    description: 'A collection of skills, tools and knowledge resources.',
    category: 'app',
    tags: ['skill', 'knowledge', 'collection'],
    href: '/lab/skill',
    featured: true,
    dataSource: 'local',
  },
];

export const labApps: LabApp[] = registeredLabApps;
