import type { LabApp } from './types';

const registeredLabApps: LabApp[] = [
  {
    slug: 'agent',
    title: 'AI助手',
    description: 'AI 对话助手，支持 api 模型调用、流式回复与文本生成图片。',
    category: 'app',
    tags: ['ai', 'chat', 'streaming'],
    href: '/lab/agent',
    featured: true,
    dataSource: 'future-backend',
  },
  {
    slug: 'mahjong',
    title: '日本麻将',
    description: '纯前端日本麻将训练游戏，支持本地人机对局、牌型图鉴与牌局复盘。',
    category: 'game',
    tags: ['game', 'mahjong', 'riichi'],
    href: '/lab/mahjong',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'gba',
    title: 'GBA emulator',
    description: '基于 WASM 与 Canvas 的 GBA 模拟器，支持本地 ROM 和浏览器存档。',
    category: 'game',
    tags: ['game', 'gba', 'wasm'],
    href: '/lab/gba',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'note',
    title: '笔记',
    description: '自由记录文本与临时备忘，内容只保存在当前浏览器。',
    category: 'tool',
    tags: ['note', 'local', 'clipboard'],
    href: '/lab/note',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'editor',
    title: '代码编辑器',
    description: '在线编辑 React 与 HTML、CSS、JavaScript，实时预览效果。',
    category: 'tool',
    tags: ['react', 'javascript', 'preview'],
    href: '/lab/editor',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'timezone',
    title: '时区工具',
    description: '根据设备时区实时显示本地与世界时间，一键复制常用代码时间格式。',
    category: 'tool',
    tags: ['timezone', 'tool', 'dayjs'],
    href: '/lab/timezone',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'maplestory',
    title: '冒险岛怪物资料',
    description: '浏览冒险岛国服怀旧服怪物的属性与掉落道具，支持本地检索和排序。',
    category: 'tool',
    tags: ['maplestory', 'monster'],
    href: '/lab/maplestory',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'sudoku',
    title: '数独',
    description: '数独游戏，支持五级难度与键盘操作。',
    category: 'game',
    tags: ['game', 'sudoku', 'logic'],
    href: '/lab/sudoku',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'rss',
    title: 'RSS Reader',
    description: '聚合你的RSS订阅',
    category: 'app',
    tags: ['rss', 'reader', 'feed'],
    href: '/lab/rss',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'minesweeper',
    title: '扫雷',
    description: '经典扫雷游戏，支持预设与自定义难度。',
    category: 'game',
    tags: ['game', 'minesweeper'],
    href: '/lab/minesweeper',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'rpg',
    title: 'Adventure',
    description: '文字挂机冒险RPG游戏，选择职业，自动战斗，收集装备！',
    category: 'game',
    tags: ['game', 'rpg', 'idle'],
    href: '/lab/rpg',
    featured: true,
    dataSource: 'local',
  },
  {
    slug: 'skill',
    title: 'Skill',
    description: 'Skills 资源集合，提供技能、知识、工具等内容的快速访问。',
    category: 'app',
    tags: ['skill', 'knowledge', 'collection'],
    href: '/lab/skill',
    featured: true,
    dataSource: 'local',
  },
];

export const labApps: LabApp[] = registeredLabApps;
